export const card_images = [
  "https://images-eu.ssl-images-amazon.com/images/G/31/IMG15/Irfan/GATEWAY/MSO/Appliances-QC-PC-186x116--B08RDL6H79._SY116_CB667322346_.jpg",
  "https://images-eu.ssl-images-amazon.com/images/G/31/IMG15/Irfan/GATEWAY/MSO/Appliances-QC-PC-186x116--B08345R1ZW._SY116_CB667322346_.jpg",
  "https://images-eu.ssl-images-amazon.com/images/G/31/IMG15/Irfan/GATEWAY/MSO/Appliances-QC-PC-186x116--B07G5J5FYP._SY116_CB667322346_.jpg",
  "https://images-eu.ssl-images-amazon.com/images/G/31/IMG15/Irfan/GATEWAY/MSO/186x116---wm._SY116_CB667322346_.jpg",
  "https://images-eu.ssl-images-amazon.com/images/G/31/img22/Fashion/Gateway/BAU/BTF-Refresh/May/PF_MF/MF-1-186-116._SY116_CB636110853_.jpg",
  "https://images-eu.ssl-images-amazon.com/images/G/31/img22/Fashion/Gateway/BAU/BTF-Refresh/May/PF_MF/MF-2-186-116._SY116_CB636110853_.jpg",
  "https://images-eu.ssl-images-amazon.com/images/G/31/img22/Fashion/Gateway/BAU/BTF-Refresh/May/PF_MF/MF-3-186-116._SY116_CB636110853_.jpg",
  "https://images-eu.ssl-images-amazon.com/images/G/31/img22/Fashion/Gateway/BAU/BTF-Refresh/May/PF_MF/MF-4-186-116._SY116_CB636110853_.jpg",
  "https://images-eu.ssl-images-amazon.com/images/G/31/img21/MSO/CE/Unrec1/Boat_Desktop_Qc_1x._SY116_CB577919562_.jpg",
  "https://images-eu.ssl-images-amazon.com/images/G/31/img21/MSO/CE/Unrec1/Boult_Desktop_Qc_1x._SY116_CB577919562_.jpg",
  "https://images-eu.ssl-images-amazon.com/images/G/31/img21/MSO/CE/Unrec1/Noise_Desktop_Qc_1x._SY116_CB577919562_.jpg",
  "https://images-eu.ssl-images-amazon.com/images/G/31/img21/MSO/CE/Unrec1/Zebronics_Desktop_Qc_1x._SY116_CB577919562_.jpg",
  " https://m.media-amazon.com/images/I/61LAuZ-bdoL._AC_SX300_SY250_.jpg ",
  " https://m.media-amazon.com/images/S/al-eu-726f4d26-7fdb/e52c362a-e087-4296-b4af-e51493d3c152._CR0,0,1200,400_AC_SX300_SY250_.png",
  "https://images-eu.ssl-images-amazon.com/images/G/31/img23/HI/SYED/ATF/QC-adapts_186x116_4._SY116_CB600489960_.jpg",
  "https://images-eu.ssl-images-amazon.com/images/G/31/img23/HI/SYED/ATF/QC-adapts_186x116_3._SY116_CB600489960_.jpg",
  "https://images-eu.ssl-images-amazon.com/images/G/31/img23/HI/SYED/ATF/QC-adapts_186x116_7._SY116_CB600489960_.jpg",
  "https://images-eu.ssl-images-amazon.com/images/G/31/img23/HI/SYED/ATF/QC-adapts_186x116_5._SY116_CB600489960_.jpg",
  "https://images-eu.ssl-images-amazon.com/images/G/31/img22/Fashion/Gateway/BAU/BTF-Refresh/May/PC_WF/WF1-186-116._SY116_CB636048992_.jpg",
  "https://images-eu.ssl-images-amazon.com/images/G/31/img22/Fashion/Gateway/BAU/BTF-Refresh/May/PC_WF/WF2-186-116._SY116_CB636048992_.jpg",
  "https://images-eu.ssl-images-amazon.com/images/G/31/img22/Fashion/Gateway/BAU/BTF-Refresh/May/PC_WF/WF4-186-116._SY116_CB636048992_.jpg",
  "https://images-eu.ssl-images-amazon.com/images/G/31/img22/Fashion/Gateway/BAU/BTF-Refresh/May/PC_WF/WF3-186-116._SY116_CB636048992_.jpg",
  "https://images-eu.ssl-images-amazon.com/images/G/31/IMG20/Home/2024/Gateway/BTFGW/PCQC/186x116_Home_furnishings_2._SY116_CB584596691_.jpg",
  "https://images-eu.ssl-images-amazon.com/images/G/31/IMG20/Home/2024/Gateway/BTFGW/PCQC/186x116_Home_decor_1._SY116_CB584596691_.jpg",
  "https://images-eu.ssl-images-amazon.com/images/G/31/IMG20/Home/2024/Gateway/BTFGW/PCQC/186x116_Home_storage_1._SY116_CB584596691_.jpg",
  "https://images-eu.ssl-images-amazon.com/images/G/31/IMG20/Home/2024/Gateway/BTFGW/PCQC/186x116_Home_lighting_2._SY116_CB584596691_.jpg",
  "https://images-eu.ssl-images-amazon.com/images/G/31/img17/Auto/2020/GW/PCQC/Glasscare1X._SY116_CB410830553_.jpg",
  "https://images-eu.ssl-images-amazon.com/images/G/31/img17/Auto/2020/GW/PCQC/Rim_tyrecare1x._SY116_CB410830552_.jpg",
  "https://images-eu.ssl-images-amazon.com/images/G/31/img17/Auto/2020/GW/PCQC/Vega_helmet_186x116._SY116_CB405090404_.jpg",
  "https://images-eu.ssl-images-amazon.com/images/G/31/img17/Auto/2020/GW/PCQC/Vaccum1x._SY116_CB410830552_.jpg",
];
export const carouselRow = [
  {
    id: 1,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/4105IiC5tDL._AC_SY200_.jpg",
    offer: "45% off",
    limited: "Limited time deal",
    offeredPrice: "10,999.00",
    rupeeSymbol: "₹",
    originalPrice: "M.R.P.: ₹23,999.00",
    pro_details: "iQ00 Z6s Lite | Starting @10999 inc...",
  },
  {
    id: 2,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/41bLD50sZSL._AC_SY200_.jpg",
    offer: "38% off",
    limited: "Limited time deal",
    offeredPrice: "14,999.00",
    rupeeSymbol: "₹",
    originalPrice: "M.R.P.: ₹23,999.00",
    pro_details: "iQ00 Z7s 5G | Starting @13999 inc...",
  },
  {
    id: 3,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/512Poa0iMkL._AC_SY200_.jpg",
    offer: "up to 75% off",
    limited: "Limited time deal",
    offeredPrice: "",
    rupeeSymbol: "",
    originalPrice: "",
    pro_details: "Best Selling Home Products by Kuber Industries",
  },
  {
    id: 4,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/91hc2MZSYlL._AC_SY200_.jpg",
    offer: "up to 79% off",
    limited: "Limited time deal",
    offeredPrice: "",
    rupeeSymbol: "",
    originalPrice: "",
    pro_details: "Menswear: Blackberrys, Levi's, Spykar and more",
  },
  {
    id: 5,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/31agL1j3cHL._AC_SY200_.jpg",
    offer: "up to 65% off",
    limited: "Limited time deal",
    offeredPrice: "",
    rupeeSymbol: "",
    originalPrice: "",
    pro_details: "Safety and Security",
  },
  {
    id: 6,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/21Y8QZTRJBL._AC_SY200_.jpg",
    offer: "up to 45% off",
    limited: "Limited time deal",
    offeredPrice: "",
    rupeeSymbol: "",
    originalPrice: "",
    pro_details: "Cleaning Supplies",
  },
  {
    id: 7,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/31e1ZcqiwTL._AC_SY200_.jpg",
    offer: "up to 40% off",
    limited: "Limited time deal",
    offeredPrice: "",
    rupeeSymbol: "",
    originalPrice: "",
    pro_details: "Water Dispensers &amp; Filters",
  },
  {
    id: 8,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/91dovXuONBL._AC_SY200_.jpg",
    offer: "up to 83% off",
    limited: "Limited time deal",
    offeredPrice: "",
    rupeeSymbol: "",
    originalPrice: "",
    pro_details: "All Clothing: BIBA, Max, Aurelia and more.",
  },
  {
    id: 9,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/41TssgTTkwL._AC_SY200_.jpg",
    offer: "up to 53% off",
    limited: "Limited time deal",
    offeredPrice: "",
    rupeeSymbol: "",
    originalPrice: "",
    pro_details: "Best Offers from Top Brands",
  },
  {
    id: 10,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/41CtKtA3+aL._AC_SY200_.jpg",
    offer: "up to 75% off",
    limited: "Limited time deal",
    offeredPrice: "",
    rupeeSymbol: "",
    originalPrice: "",
    pro_details: "Best Offers on Home and Storage Products",
  },
  {
    id: 11,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/618I++aMUNL._AC_SY200_.jpg",
    offer: "up to 87% off",
    limited: "Limited time deal",
    offeredPrice: "",
    rupeeSymbol: "",
    originalPrice: "",
    pro_details: "Casual Wear Tops from Top Brands",
  },
  {
    id: 12,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/41uGjvXbeBL._AC_SY200_.jpg",
    offer: "up to 94% off",
    limited: "Limited time deal",
    offeredPrice: "",
    rupeeSymbol: "",
    originalPrice: "",
    pro_details: "Travel Adapters And Electronic Accessories from RTS",
  },
  {
    id: 13,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/31-TqE7SqjL._AC_SY200_.jpg",
    offer: "up to 77% off",
    limited: "Limited time deal",
    offeredPrice: "",
    rupeeSymbol: "",
    originalPrice: "",
    pro_details: "Best Offers on Destinio Travel Accessories",
  },
  {
    id: 14,
    link: "#",
    imageID:
      "https://m.media-amazon.com/images/I/71JE6RVeu3L._SY695__AC_SY200_.jpg",
    offer: "up to 60% off",
    limited: "Limited time deal",
    offeredPrice: "",
    rupeeSymbol: "",
    originalPrice: "",
    pro_details: "Best Deals on Puma",
  },
  {
    id: 15,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/41h5U0ROy6L._AC_SY200_.jpg",
    offer: "up to 50% off",
    limited: "Limited time deal",
    offeredPrice: "",
    rupeeSymbol: "",
    originalPrice: "",
    pro_details: "Best Deals on Asian",
  },
];
export const row3 = [
  {
    id: 1,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/51NfD0YtIgL._AC_SY200_.jpg",
    alt: "Borosil Classic Glass Tea Set, Flame Proof &amp; Microwave Proof, Clear",
  },
  {
    id: 2,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/71Jb6Uxtb7L._AC_SY200_.jpg",
    alt: "Indian Art Villa Bronze | 6 Piece Dinner Thali Set with 2 Bowl 1 Rice Plate 1 Glass and 1 Spoon",
  },
  {
    id: 3,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/61W4kKARkzL._AC_SY200_.jpg",
    alt: "KitchenAid 5KSM7591XBWH Professional 500 - Watt Bowl Lift Stand Mixer 6.9 Litre - White",
  },
  {
    id: 4,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/41GHF5B2DNL._AC_SY200_.jpg",
    alt: "OTG 23 LTR",
  },
  {
    id: 5,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/716dK-6EcIL._AC_SY200_.jpg",
    alt: "Cello Opalware Dazzle Series Scarlet Bliss Dinner Set, 37 Units | Opal Glass Dinner Set | Light-Weight, Daily Use...",
  },
  {
    id: 6,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/81-zUhClFUL._AC_SY200_.jpg",
    alt: "Mollismoons Bean Bag with Beans Bean Bag Pink XXXL Size Filled Bean Bag Pink Color (Faux Fur)",
  },
  {
    id: 7,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/51o5kukpXsL._AC_SY200_.jpg",
    alt: "BLACK OAK 2 Seater Organizer Storage Ottoman Bench Footrest Stool Coffee Table Luper Tufted Storage Ottoman Large with...",
  },
  {
    id: 8,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/71u6qOaVvDL._AC_SY200_.jpg",
    alt: "Tobeelec Pasta Maker, Stainless Steel Manual Pasta Machine with 7 Adjustable Thickness Settings Noodles Cutter for...",
  },
  {
    id: 9,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/610aK9cLn5L._AC_SY200_.jpg",
    alt: "Hawkins Stainless Steel Contura Induction Compatible Inner Lid Pressure Cooker, 5 Litre, Silver (Ssc50), 5 Liter",
  },
  {
    id: 10,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/51qFwdsVPlL._AC_SY200_.jpg",
    alt: "You God Electric Pizza Pan Non Stick Coating Fry Pan (1 Year Warranty), Pack of 1, Black Color",
  },
  {
    id: 11,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/51GyBEt+DDS._AC_SY200_.jpg",
    alt: "PRATHAM INDIA Iron &amp; Wicker Single Seater Swing Chair with Stand &amp; Cushion &amp; Hook",
  },
  {
    id: 12,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/91rcvPCASyL._AC_SY200_.jpg",
    alt: "Wood Maker Winsley Storage Ottoman Bench, Sofa Bench, Footstool, Bed End Table, Settee, with Storage for Living Room,...",
  },
  {
    id: 13,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/71PRTX4wwzL._AC_SY200_.jpg",
    alt: "BINZO Glass Kettle with Cup Set and Wooden Tray for Tea, Coffee, Set of 4 Cups, Borosilicate Glass Teapot with Bamboo...",
  },
  {
    id: 14,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/81+fVbIHPvL._AC_SY200_.jpg",
    alt: "JustBrew® Crystal Skyline Teapot and Cup Set of 5 (1100ml) | Borosilicate Glass Tea Pot with 4 Cups | Drinkware with...",
  },
  {
    id: 15,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/51NfD0YtIgL._AC_SY200_.jpg",
    alt: "Borosil Classic Glass Tea Set, Flame Proof &amp; Microwave Proof, Clear",
  },
];
export const row4 = [
  {
    id: 1,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/71IB+2LNNBL._AC_SY200_.jpg",
    alt: "Presto! Garbage Bags, Medium - (19 x 21 Inches) - 30 Bags/Roll, 180 Count (Pack Of 6, Black), Plastic",
  },
  {
    id: 2,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/51RXzjrUmkL._AC_SY200_.jpg",
    alt: "Pigeon Polypropylene Mini Handy and Compact Chopper with 3 Blades for Effortlessly Chopping Vegetables and Fruits for...",
  },
  {
    id: 3,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/410a9N3gxpL._AC_SY200_.jpg",
    alt: "JIALTO Adhesive Hooks Heavy Duty Wall Hooks, Nail Hook for Hanging Coat, Hat,Towel Robe Hook Rack Wall Mount- Bathroom...",
  },
  {
    id: 4,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/71erHCKJ3WL._AC_SY200_.jpg",
    alt: "Ezee Black Garbage Bags for Dustbin | 90 Pcs | Medium 19 X 21 Inches | 30 Pcs x Pack of 3",
  },
  {
    id: 5,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/61Is7sICRJL._AC_SY200_.jpg",
    alt: "beatXP Kitchen Scale Multipurpose Portable Electronic Digital Weighing Scale | Weight Machine With Back light LCD...",
  },
  {
    id: 6,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/7152-mn8mKL._AC_SY200_.jpg",
    alt: "NutriPro Juicer Mixer Grinder - Smoothie Maker - 500 Watts (3 Jar 2 Blade)",
  },
  {
    id: 7,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/71zjvUApaRL._AC_SY200_.jpg",
    alt: "Homestrap Set of 6 Non-Woven Printed Saree Cover/Cloth Storage/Organizer with Transparent Window (Grey)(Featured on...",
  },
  {
    id: 8,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/71rF75hKX5L._AC_SY200_.jpg",
    alt: "Shalimar Premium Garbage Bags (Medium) Size 19 x 21 Inches 4 Rolls 120 Bags Dustbin Bag/Trash Bag - Black Color",
  },
  {
    id: 9,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/61y6iRvb-WL._AC_SY200_.jpg",
    alt: "Wakefit Height Adjustable Hollow Fibre Sleeping Pillow with Zip | Set of 2 (White and Grey, 27 x 16 Inches) 3 Months...",
  },
  {
    id: 10,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/71rGmZ+DKcL._AC_SY200_.jpg",
    alt: "Status Contract Anti Slip Front Door Mat|(38x58cm) Living Room Rug for Entrance Door|Polypropylene Floor Mat for...",
  },
  {
    id: 11,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/61sRf7oDELL._AC_SY200_.jpg",
    alt: "Wakefit 100% Waterproof Premium Cotton Mattress Protector | Breathable and Hypoallergenic Ultra Soft Fitted Bed...",
  },
  {
    id: 12,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/6121tV2hW9L._AC_SY200_.jpg",
    alt: "Godrej aer Matic Kit (Machine + 1 Refill) - Automatic Room Fresheners with Flexi Control Spray | Violet Valley Bloom |...",
  },
  {
    id: 13,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/81yobRRV8nL._AC_SY200_.jpg",
    alt: "Cookwell Bullet Mixer Grinder (5 Jar, 3 Blade, Silver)",
  },
  {
    id: 14,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/816lZp-8R2L._AC_SY200_.jpg",
    alt: "Bajaj Pygmy Mini Fan 110mm | USB Charging Fan | Multi-Clip Function | Rechargeable Fan| Battery Fan| 4-Hr Back-up|...",
  },
  {
    id: 15,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/51Da+TBexCL._AC_SY200_.jpg",
    alt: "MILTON Aqua 1000 Stainless Steel Water Bottle, 1 pc, 950 ml, Silver",
  },
];
export const cardRow2 = [
  {
    title: "Keep shopping for",
    img1: "https://m.media-amazon.com/images/I/81WV6JJskCL._AC_SY95_.jpg",
    description1:
      "Sipologie Inspire Tea Pot with Infuser 400ml, Glass Tea Kettle for Gas Stove, Flame Proof Glass Kettle for Tea, Fine...",
    symbol: "₹",
    zero: "00",
    price1: "897",
    img2: "https://m.media-amazon.com/images/I/51hZLauf9XL._AC_SY95_.jpg",
    price2: "682",
    description2:
      "Borosil - Carafe Flame Proof Glass Kettle With Stainer, 1L, transparent (IH11KF09210)",
    img3: "https://m.media-amazon.com/images/I/51XtQSdwKZL._AC_SY95_.jpg",
    price3: "516",
    description3:
      "Borosil - Carafe Flame Proof Glass Kettle With Stainer, 650 ml",
    img4: "https://m.media-amazon.com/images/I/61UAS+u1itL._AC_SY95_.jpg",
    price4: "723",
    description4:
      "Borosil - Carafe Flame Proof Glass Kettle with Stainer, 1.2L",
    footer: "See more",
    id: 1,
  },
];
export const row5 = [
  {
    id: 1,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/816uleHZdTL._AC_SY200_.jpg",
    alt: "INDIGENOUS HONEY Raw Organic Honey NMR Tested NPOP Organic Certified Pure Natural Unprocessed Original Honey - 530 g...",
  },
  {
    id: 2,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/91PTkeKPvvL._AC_SY200_.jpg",
    alt: "Phool Holi Colour - Braj Collection with Mishrambu Premium Thandai I (Pink, Green, Blue, Yellow) I Skin Friendly &amp; Easy...",
  },
  {
    id: 3,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/81xmrQ9UWKL._AC_SY200_.jpg",
    alt: "ALPINO High Protein Super Rolled Oats Chocolate - Rolled Oats, Natural Peanut Butter &amp; Cocoa Powder – 21g Protein, No...",
  },
  {
    id: 4,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/71zRgmoMoqL._AC_SY200_.jpg",
    alt: "ALPINO Natural Peanut Butter Crunch 1kg - 100% Roasted Peanuts - 30g Protein, No Added Sugar &amp; Salt, non-GMO, Gluten...",
  },
  {
    id: 5,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/61-PrwKggAL._AC_SY200_.jpg",
    alt: "First Bud Organics - Lakadong Turmeric Powder (250g) | ( 7-12) % High Curcumin Content | Unprocessed and Organic Haldi...",
  },
  {
    id: 6,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/81hSomS9mdL._AC_SY200_.jpg",
    alt: "ALPINO High Protein Super Rolled Oats Chocolate - Rolled Oats, Natural Peanut Butter &amp; Cocoa Powder – 21g Protein, No...",
  },
  {
    id: 7,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/51+beNkqKeL._AC_SY200_.jpg",
    alt: "First Bud Organics - Homemade Mango Pickle (500g) | Secret Rajasthani Recipe | Dry and Spicy Pickle | 100% Natural...",
  },
  {
    id: 8,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/81jlZOq8WAL._AC_SY200_.jpg",
    alt: "Snowpeak Chai Masala | Aromatic Tea Masala Powder with 100% Natural Spices | Pack of 4 x 50 Gm (200 gram)",
  },
  {
    id: 9,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/61kvVLfiC4L._AC_SY200_.jpg",
    alt: "MBDH Wellness Ignite Chocolate Bars (1 Box), Luxurious Blueberry Flavour Chocolate For Uplifting Mood &amp; Vitality, Ideal...",
  },
  {
    id: 10,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/71pRmjfk0HL._AC_SY200_.jpg",
    alt: "Fit &amp; Flex Baked Multigrain Lemony Mint, Tangy Tomato &amp; Cheesy Cheese Namkeen Mixture, Healthy Snacks With Zero...",
  },
  {
    id: 11,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/711MdW6OIML._AC_SY200_.jpg",
    alt: "Snowpeak Dosti Hot Imli Candy | Tamarind Candy | Digestive Candy | 220 Pieces (Pack of 1)",
  },
  {
    id: 12,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/61nDAvgSVVL._AC_SY200_.jpg",
    alt: "ALPINO Chocolate Peanut Butter Smooth 200 G - Roasted Peanuts, Chocolate Paste, Brown Sugar &amp; Sea Salt - 24g Protein,...",
  },
];
export const row6 = [
  {
    id: 1,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/71nnPSdLxIL._AC_SY200_.jpg",
    alt: "MCLORD Aqua Royal RO Domestic Water Purifier | RO+ LED UV+ ORC COPPER+ ZINC+ ALKALINE+ HIGH TDS MEMBRANE+ TDS CONTROL |...",
  },
  {
    id: 2,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/817mA3uug7L._AC_SY200_.jpg",
    alt: "Dreamydesks Solid Sheesham Wood 2 Seater Sofa, 2 Seater Sofa Set with Side Pockets with Cushions for Living Room, Home...",
  },
  {
    id: 3,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/81Cyvo830iL._AC_SY200_.jpg",
    alt: "Dreamydesks Solid Sheesham Wood 2 Seater Sofa, 2 Seater Sofa Set with Side Pockets with Cushions for Living Room, Home...",
  },
  {
    id: 4,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/817mA3uug7L._AC_SY200_.jpg",
    alt: "Dreamydesks Solid Sheesham Wood 2 Seater Sofa, 2 Seater Sofa Set with Side Pockets with Cushions for Living Room, Home...",
  },
  {
    id: 5,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/81I+ohnBGLL._AC_SY200_.jpg",
    alt: "Dreamydesks Solid Sheesham Wood 2 Seater Sofa, 2 Seater Sofa Set with Side Pockets with Cushions for Living Room, Home...",
  },
  {
    id: 6,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/81CjNv-wrGL._AC_SY200_.jpg",
    alt: "BRISHI Garden Patio Seating Chair and Table Set Outdoor Balcony Garden Coffee Table Set Furniture with 1 Table and 2...",
  },
  {
    id: 7,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/51EMgNSP5AL._AC_SY200_.jpg",
    alt: "Dreamydesks Solid Sheesham Wood Bedside Table with 2 Drawer &amp; 1 Shelf Storage for Bedroom, End Table, Side Table for...",
  },
  {
    id: 8,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/711lHXUrW7L._AC_SY200_.jpg",
    alt: "Dreamydesks Solid Sheesham Wood King Size Bed with Box Storage for Bedroom, Wooden Double Bed, Palang for Home Decor -...",
  },
  {
    id: 9,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/61y6iRvb-WL._AC_SY200_.jpg",
    alt: "Wakefit Height Adjustable Hollow Fibre Sleeping Pillow with Zip | Set of 2 (White and Grey, 27 x 16 Inches) 3 Months...",
  },
  {
    id: 10,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/71rGmZ+DKcL._AC_SY200_.jpg",
    alt: "Status Contract Anti Slip Front Door Mat|(38x58cm) Living Room Rug for Entrance Door|Polypropylene Floor Mat for...",
  },
  {
    id: 11,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/61sRf7oDELL._AC_SY200_.jpg",
    alt: "Wakefit 100% Waterproof Premium Cotton Mattress Protector | Breathable and Hypoallergenic Ultra Soft Fitted Bed...",
  },
  {
    id: 12,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/81XN+lNAL5L._AC_SY200_.jpg",
    alt: "Sofa Architect Darcy 3+2 5 Seater Sofa Set (Grey)",
  },
  {
    id: 13,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/71gpVameiQL._AC_SY200_.jpg",
    alt: "MCLORD Aqua Fresh Plus RO Domestic Water Purifier (RO+ LED UV+ COPPER+ HIGH TDS MEMBRANE+ TDS CONTROL) Fully Automatic,...",
  },
  {
    id: 14,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/813rvU2HhHL._AC_SY200_.jpg",
    alt: "ZARYAN ORIENTAL CARPETS_Soft Fluffy Shag Area Rugs for Living Room, Shaggy Floor Carpet for Bedroom, Girls Carpets Kids...",
  },
  {
    id: 15,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/91FMJYV7lHL._AC_SY200_.jpg",
    alt: "ZARYAN ORIENTAL CARPETS_Soft Fluffy Shag Area Rugs for Living Room, Shaggy Floor Carpet for Bedroom, Girls Carpets Kids...",
  },
  {
    id: 16,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/91B-+XLLdUS._AC_SY200_.jpg",
    alt: "ZARYAN ORIENTAL CARPETS_Soft Fluffy Shag Area Rugs for Living Room, Shaggy Floor Carpet for Bedroom, Girls Carpets Kids...",
  },
  {
    id: 17,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/91rWEqqr9rS._AC_SY200_.jpg",
    alt: "ZARYAN ORIENTAL CARPETS_Soft Fluffy Shag Area Rugs for Living Room, Shaggy Floor Carpet for Bedroom, Girls Carpets Kids...",
  },
  {
    id: 18,
    link: "#",
    imageID: "https://m.media-amazon.com/images/I/A14rJo-oQUS._AC_SY200_.jpg",
    alt: "ZARYAN ORIENTAL CARPETS_Soft Fluffy Shag Area Rugs for Living Room, Shaggy Floor Carpet for Bedroom, Girls Carpets Kids...",
  },
];
export const Row7 = [
  {
    id: 1,
    link: "#",
    imageID:
      "https://images-na.ssl-images-amazon.com/images/I/41wkJAz0U6L._SX160_QL100_AC_SCLZZZZZZZ_.jpg",
    offer: "",
    limited: "",
    offeredPrice: "331.00",
    rupeeSymbol: "₹",
    originalPrice: "M.R.P.: ₹430.00",
    pro_details:
      "Biotique Ocean Kelp Anti Hairfall Shampoo | Intensive Hair Growth Therapy| Anti Hairfall Shampoo that Maintains Shine |100% Botanical Extracts | Suitable for All Hair Types |650ml",
  },
  {
    id: 2,
    link: "#",
    imageID:
      "https://images-na.ssl-images-amazon.com/images/I/41S2dWblbyL._SX160_QL100_AC_SCLZZZZZZZ_.jpg",
    offer: "",
    limited: "",
    offeredPrice: "283.00",
    rupeeSymbol: "₹",
    originalPrice: "M.R.P.: ₹315.00",
    pro_details:
      "Matrix Opti.Care Professional  Conditioner for Salon Smooth Straight Hair | Control Frizzy Hair for up to 4 Days | With Shea Butter | No Added Parabens | (98 g)",
  },
  {
    id: 3,
    link: "#",
    imageID:
      "https://images-na.ssl-images-amazon.com/images/I/31nV71qHxXL._SX160_QL100_AC_SCLZZZZZZZ_.jpg",
    offer: "5% off",
    limited: "Limited time deal",
    offeredPrice: "351.00",
    rupeeSymbol: "₹",
    originalPrice: "M.R.P.: ₹370.00",
    pro_details:
      "Biolage Smoothproof Conditioner For Frizzy Hair | Provides Humidity Control &amp; Anti-Frizz Smoothness | With Camellia Flower | Natural &amp; Vegan (196gms)",
  },
  {
    id: 4,
    link: "#",
    imageID:
      "https://images-na.ssl-images-amazon.com/images/I/31NEzFUBxQL._SX160_QL100_AC_SCLZZZZZZZ_.jpg",
    offer: "11% off",
    limited: "Limited time deal",
    offeredPrice: "258.00",
    rupeeSymbol: "₹",
    originalPrice: "M.R.P.: ₹290.00",
    pro_details:
      "MATRIX Opti Long Professional Conditioner | Detangled and nourished long hair | With Ceramide | For Long hair 98g",
  },
  {
    id: 5,
    link: "#",
    imageID:
      "https://images-na.ssl-images-amazon.com/images/I/31SNU6Llx4L._SX160_QL100_AC_SCLZZZZZZZ_.jpg",
    offer: "16% off",
    limited: "Limited time deal",
    offeredPrice: "365.00",
    rupeeSymbol: "₹",
    originalPrice: "M.R.P.: ₹435.00",
    pro_details:
      "Biolage Smoothproof Professional 2-Step Regime Used in Salons | Shampoo + Conditioner for Frizz-Free Hair for up to 72 HRS | Enriched with Camellia Flowers | Natural &amp; No Added Parabens (200ml + 98g)",
  },
  {
    id: 6,
    link: "#",
    imageID:
      "https://images-na.ssl-images-amazon.com/images/I/41vp4xvVLzL._SX160_QL100_AC_SCLZZZZZZZ_.jpg",
    offer: "11% off",
    limited: "Limited time deal",
    offeredPrice: "280.00",
    rupeeSymbol: "₹",
    originalPrice: "M.R.P.: ₹315.00",
    pro_details:
      "Matrix Opti.Repair Professional Liquid Protein Conditioner | Repairs Damage from 1st Use | for Damaged High Porosity Hair, Split Ends, Breakage",
  },
  {
    id: 7,
    link: "#",
    imageID:
      "https://images-na.ssl-images-amazon.com/images/I/31cBo3xQHhL._SX160_QL100_AC_SCLZZZZZZZ_.jpg",
    offer: "25% off",
    limited: "Limited time deal",
    offeredPrice: "262.00",
    rupeeSymbol: "₹",
    originalPrice: "M.R.P.: ₹349.00",
    pro_details:
      "Clensta Rosemary Hair Fall Control Shampoo with Biotin for Reducing Hair Loss, Breakage &amp; Daily use |All Hair Types | Men &amp; Women | Sulfate &amp; Paraben Free 250ml",
  },
  {
    id: 8,
    link: "#",
    imageID:
      "https://images-na.ssl-images-amazon.com/images/I/413w56ZpN4L._SX160_QL100_AC_SCLZZZZZZZ_.jpg",
    offer: "20% off",
    limited: "Limited time deal",
    offeredPrice: "319.00",
    rupeeSymbol: "₹",
    originalPrice: "M.R.P.: ₹400.00",
    pro_details:
      "PLIX - THE PLANT FIX Rosemary Advanced Anti HairFall Shampoo for Decreases Hair Fall &amp; Breakage - 200 ml | All Hair Types | Men &amp; Women | Sulphate &amp; Paraben Free",
  },
  {
    id: 9,
    link: "#",
    imageID:
      "https://images-na.ssl-images-amazon.com/images/I/31KrQuQWcRL._SX160_QL100_AC_SCLZZZZZZZ_.jpg",
    offer: "25% off",
    limited: "Limited time deal",
    offeredPrice: "374.00",
    rupeeSymbol: "₹",
    originalPrice: "M.R.P.: ₹499.00",
    pro_details:
      "Clensta Rosemary Hair Fall Control Mask With Biotin For Reducing Hair fall, Dandruff, Strengthens Hair &amp; Daily use |All Hair Types | Men &amp; Women | Sulfate &amp; Paraben Free 200 gm",
  },
  {
    id: 10,
    link: "#",
    imageID:
      "https://images-na.ssl-images-amazon.com/images/I/31VtyeK1LoL._SX160_QL100_AC_SCLZZZZZZZ_.jpg",
    offer: "10% off",
    limited: "Limited time deal",
    offeredPrice: "270.00",
    rupeeSymbol: "₹",
    originalPrice: "M.R.P.: ₹300.00",
    pro_details:
      "Fixderma Face21 Cleanser, Skin Brightening Cleanser, Exfoliates Dead Cells, Remove Pigmentation, Reduces Wrinkles &amp; Fine Lines, Evens Skin Tone, Purifies Skin, 75ml",
  },
  {
    id: 11,
    link: "#",
    imageID:
      "https://images-na.ssl-images-amazon.com/images/I/31cn6u1mZWL._SX160_QL100_AC_SCLZZZZZZZ_.jpg",
    offer: "12% off",
    limited: "Limited time deal",
    offeredPrice: "275.00",
    rupeeSymbol: "₹",
    originalPrice: "M.R.P.: ₹380.00",
    pro_details:
      "Tresemme Keratin Smooth, Conditioner, 335ml, for Smoother, Shinier Hair, with Keratin &amp; Moroccan Argan Oil, Nourishes &amp; Controls Frizz, up to 72 Hours, for Men &amp; Women",
  },
  {
    id: 12,
    link: "#",
    imageID:
      "https://images-na.ssl-images-amazon.com/images/I/41F9mnAFUHL._SX160_QL100_AC_SCLZZZZZZZ_.jpg",
    offer: "",
    limited: "",
    offeredPrice: "559.00",
    rupeeSymbol: "₹",
    originalPrice: "",
    pro_details:
      "Dove Beautiful Curls Deep Moisture Miracle Floral Fragrance Hair Mask for Curly Hair 300 ml",
  },
  {
    id: 13,
    link: "#",
    imageID:
      "https://images-na.ssl-images-amazon.com/images/I/41O5mg-SzcL._SX160_QL100_AC_SCLZZZZZZZ_.jpg",
    offer: "5% off",
    limited: "Limited time deal",
    offeredPrice: "295.00",
    rupeeSymbol: "₹",
    originalPrice: "M.R.P.: ₹310.00",
    pro_details:
      "Streax Professional Spa Nourishment Hair Masque For Women | Normal To Dry Hair | Enriched With Honey &amp; Vitamin E | Conditions, Softens &amp; Detangles Hair | Reveals Softer, Smoother &amp; Shinier Hair, 200 g",
  },
  {
    id: 14,
    link: "#",
    imageID:
      "https://images-na.ssl-images-amazon.com/images/I/41R0kewuOrL._SX160_QL100_AC_SCLZZZZZZZ_.jpg",
    offer: "",
    limited: "",
    offeredPrice: "499.00",
    rupeeSymbol: "₹",
    originalPrice: "",
    pro_details:
      "Tru Hair Protein Serum With Onion Extract, Biotin, Caffiene Fights Hair Thinning, Promotes Thicker Hair |Natural, Vegan and Free from Parabens, Sulphates and LLPs - 50 Ml",
  },
  {
    id: 15,
    link: "#",
    imageID:
      "https://images-na.ssl-images-amazon.com/images/I/314SU3PohmL._SX160_QL100_AC_SCLZZZZZZZ_.jpg",
    offer: "10% off",
    limited: "Limited time deal",
    offeredPrice: "470.00",
    rupeeSymbol: "₹",
    originalPrice: "M.R.P.: ₹599.00",
    pro_details:
      "TRESemme Gloss Ultimate Ultra Shine Hair Serum 100ml with Macadamia Oil &amp; Vitamin E, for Super shiny Finish",
  },
];

export const row8 = [
  {
    id: 0,
    obj: [
      {
        Cardid: 1,
        link: "",
        image:
          "https://images-eu.ssl-images-amazon.com/images/I/61kloV1yiKL._AC_UL160_SR160,160_.jpg",
        detail:
          "Clensta Rosemary Hair Fall Control Conditioner With Rosemary &amp; Biotin For Reducing Hair Loss, Breakage &amp; Daily Use | All Hair",
        offer: "15% off",
        limited: "Limited time deal",
        offeredPrice: "297.00",
        rupeeSymbol: "₹",
        originalPrice: "M.R.P.: ₹349.00",
        delivDate: " Thursday, April 25",
        delivOffer: "FREE Delivery over ₹499.",
        amazon: "fulfilled by Amazon.",
      },
      {
        Cardid: 2,
        link: "",
        image:
          "https://images-eu.ssl-images-amazon.com/images/I/61NsJGM3TOL._AC_UL160_SR160,160_.jpg",
        detail:
          "Clensta Red Aloevera Skin Glow Daily Face Wash with 0.5% Niacinamide and Vitamin C | Face Wash for Glowing Skin, Removes Dirt",
        offer: "",
        limited: "",
        offeredPrice: "99.00",
        rupeeSymbol: "₹",
        originalPrice: "M.R.P.: ₹150.00",
        delivDate: " Thursday, April 25",
        delivOffer: "FREE Delivery over ₹499.",
        amazon: "fulfilled by Amazon.",
      },

      {
        Cardid: 3,
        link: "",
        image:
          "https://images-eu.ssl-images-amazon.com/images/I/61NqMSPjQoL._AC_UL160_SR160,160_.jpg",
        detail:
          "Plantex 2 Self-Adhesive Shelves for Corner Walls for Bathroom Organizer - Bathrom Corner Shelf with Magic Sticker (Black) Met",
        offer: "70% off",
        limited: "Limited time deal",
        offeredPrice: "659.00",
        rupeeSymbol: "₹",
        originalPrice: "M.R.P.: ₹2,178.00",
        delivDate: " Friday, April 26.",
        delivOffer: "FREE Delivery by Amazon.",
        amazon: "",
      },

      {
        Cardid: 4,
        link: "",
        image:
          "https://images-eu.ssl-images-amazon.com/images/I/61V5fHBTQ6L._AC_UL160_SR160,160_.jpg",
        detail:
          "Chillyfit Wall Hooks for Hanging Strong, 10 Pack Adhesive Hooks for Wall Heavy Duty, Wall hangings, Kitchen Accessories Items",
        offer: "85% off",
        limited: "Limited time deal",
        offeredPrice: "199.00",
        rupeeSymbol: "₹",
        originalPrice: "M.R.P.: ₹1,299.00",
        delivDate: " Thursday, April 25",
        delivOffer: "FREE Delivery over ₹499.",
        amazon: "fulfilled by Amazon.",
      },
      {
        Cardid: 5,
        link: "",
        image:
          "https://images-eu.ssl-images-amazon.com/images/I/41wK5Uo9YkL._AC_UL160_SR160,160_.jpg",
        detail:
          "Borosil Glass Milk And Sugar Pot Set, 270 Ml, 2-Pieces, Transparent",
        offer: "5% off",
        limited: "Limited time deal",
        offeredPrice: "409.00",
        rupeeSymbol: "₹",
        originalPrice: "M.R.P.: ₹500.00",
        delivDate: " Friday, April 26",
        delivOffer: "FREE Delivery over ₹499.",
        amazon: "fulfilled by Amazon.",
      },
    ],
  },
  {
    id: 1,
    obj: [
      {
        Cardid: 1,
        link: "",
        image:
          "https://images-eu.ssl-images-amazon.com/images/I/61jFwYV8wGL._AC_UL160_SR160,160_.jpg",
        detail:
          "Plantex Self Adhesive GI Steel Toilet Paper Stand/Tissue roll Hanger for Bathroom (Black - Pack of 2) Steel Toilet Paper Stand/Tissue roll Hanger for Bathroom",
        offer: "62% off",
        limited: "Limited time deal",
        offeredPrice: "299.00",
        rupeeSymbol: "₹",
        originalPrice: "M.R.P.: ₹780.00",
        delivDate: " Thursday, April 25",
        delivOffer: "FREE Delivery over ₹499.",
        amazon: "fulfilled by Amazon.",
      },

      {
        Cardid: 2,
        link: "",
        image:
          "https://images-eu.ssl-images-amazon.com/images/I/71L3JDkPITL._AC_UL160_SR160,160_.jpg",
        detail:
          "KeepCart Nonstick Oil Coral Velvet Microfiber Wipes Small Size Kitchen Dish Cleaning Magic Oil Resistant Cleaning Cloth - 15cm * 25cm",
        offer: "",
        limited: "",
        offeredPrice: "249.00",
        rupeeSymbol: "₹",
        originalPrice: "M.R.P.: ₹360.00",
        delivDate: " Friday, April 26",
        delivOffer: "FREE Delivery over ₹499.",
        amazon: "fulfilled by Amazon.",
      },

      {
        Cardid: 3,
        link: "",
        image:
          "https://images-eu.ssl-images-amazon.com/images/I/51-VxJDI3nL._AC_UL160_SR160,160_.jpg",
        detail:
          "Speedex Water Bottles Stainless Steel Water Bottle 1 Litre for School Boys Girls Gym Office Home, Leakproof, Rust free (1000 ",
        offer: "",
        limited: "",
        offeredPrice: "377.00",
        rupeeSymbol: "₹",
        originalPrice: "",
        delivDate: " Friday, April 26.",
        delivOffer: "FREE Delivery by Amazon.",
        amazon: "fulfilled by Amazon.",
      },

      {
        Cardid: 4,
        link: "",
        image:
          "https://images-eu.ssl-images-amazon.com/images/I/31SIjfdnG6L._AC_UL160_SR160,160_.jpg",
        detail:
          "FLYNGO Plastic Multipurpose Storage Holder Stand For Bathroom Toothbrush Tongue Cleaner Soap Comb Razor Shaving Kit And Toile",
        offer: "54% off",
        limited: "Limited time deal",
        offeredPrice: "275.00",
        rupeeSymbol: "₹",
        originalPrice: "M.R.P.: ₹599.00",
        delivDate: " Thursday, April 25",
        delivOffer: "FREE Delivery over ₹499.",
        amazon: "fulfilled by Amazon.",
      },

      {
        Cardid: 5,
        link: "",
        image:
          "https://images-eu.ssl-images-amazon.com/images/I/71J8-dULsfL._AC_UL160_SR160,160_.jpg",
        detail:
          "AGARO Galaxy 24 Pcs Kitchen Utensils Set, Nylon and Stainless Steel, Heat Resistant, Kitchen Cooking Utensils, Cookware Set w",
        offer: "",
        limited: "",
        offeredPrice: "1,371.00",
        rupeeSymbol: "₹",
        originalPrice: "",
        delivDate: " June 1 ",
        delivOffer: "",
        amazon: "",
      },
    ],
  },
];
